 subplot(1,10,1)
boxplot(F1);
set(gca,'YTick',[]);
 subplot(1,10,2)
boxplot(F2); 
set(gca,'YTick',[]);
subplot(1,10,3)
boxplot(F3); 
set(gca,'YTick',[]);
subplot(1,10,4)
boxplot(F4); 
set(gca,'YTick',[]);
subplot(1,10,5)
boxplot(F5);
set(gca,'YTick',[]);
subplot(1,10,6)
boxplot(F6); 
set(gca,'YTick',[]);
subplot(1,10,7)
boxplot(F7); 
set(gca,'YTick',[]);
subplot(1,10,8)
boxplot(F8); 
set(gca,'YTick',[]);
subplot(1,10,9)
boxplot(F9); 
set(gca,'YTick',[]);
subplot(1,10,10)
boxplot(F10);
set(gca,'YTick',[]);