for i=1:819
CARRIER(i).CAR=CAR(i);
CARRIER(i).DAY=DAY(i);
CARRIER(i).DESTCITY=DESTCITY(i);
CARRIER(i).MONTH=MONTH(i);
CARRIER(i).PRICE=PRICE(i);
CARRIER(i).SHIPWGT=SHIPWGT(i);
CARRIER(i).TOTALCOST=TOTALCOST(i);
CARRIER(i).YEAR=YEAR(i);
CARRIER(i).NUM=i;
end